### ISSUE TITLE
Cannot install via Yarn

### ISSUE THREAD

**Issue by lousando** [hbi99/defiant.js#103]
I am able to install via NPM, but via Yarn I get:

```bash
error defiant.js@2.0.7: The engine "node" is incompatible with this module. Expected version "9.2.0".
error Found incompatible module
```

Last version that installs via Yarn is `1.4.5`

**Comment by lousando** [comment]
Strange thing is that NPM completely ignores the engines field (I'm using Node v8.12), and installs the module anyway. Should the `engines.node` field instead read `>= 9.2.0`?

**Comment by hbi99** [comment]
Hi @lousando,
Can you please check the name in your `package.json`. Someone else has published my library under the name `defiant` and that one is now stuck with version 1.4.5.

I've contacted NpmJS.org in order to recover the name but according to them, my previous license allowed them to do that and I can't do anything about it. This is the reason I've changed the license to LGPL v3.0. Of course this has resulted in that many developers most likely have `defiant` in their `package.json`. It should be changed to `defiant.js`.

**Comment by lousando** [comment]
I have checked the `package.json` entry and it does read `defiant.js`. 
`defiant` and `defiant.js` both have a `1.4.5.` version number though:

![defiant_js](https://user-images.githubusercontent.com/1214300/47049308-c6a41b80-d151-11e8-9cf8-ff8b39f89610.png)

![defiant](https://user-images.githubusercontent.com/1214300/47049309-c6a41b80-d151-11e8-9212-893e0df27d46.png)

(Source: https://semver.npmjs.com/)

**Comment by hbi99** [comment]
Ok...after installing with NPM, does Defiant v2.0+ do what you want?
The reason I have set engine to 9.2.0 is because I tested it with that version. Now according to this list:
https://node.green/

...I could set it to `7.10.1` but I have not dared. In the new version I am primarily using ES6 syntax a lot. I am pretty sure it has been supported in v7.+

If all works for you, I can set the engine v8.12, if you verify.
Another option is to omit engine version - but I think there are benefits to declaring it. What do you think?

**Comment by lousando** [comment]
@hbi99 I'd rather a [Travis](https://travis-ci.org/) build be setup so it can be [tested with multiple node versions](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/) first.

**Comment by ketysek** [comment]
@hbi99 I'm using node v8.11.3 and I'm unable to install defiant.js via yarn. Errors below:

> error defiant.js@2.1.2: The engine "node" is incompatible with this module. Expected version "7.10.1".
> error Found incompatible module

**Comment by ketysek** [comment]
@hbi99 I've created a PR #105 to set v 7.10.1 as minimal, not the only one allowed.

**Comment by ketysek** [comment]
@hbi99 is puppeteer required for production build of the library? Because my app now doesn't compile:

```
Failed to compile.
./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Can't resolve 'ws' in '/frontend/node_modules/puppeteer/lib'
```
