### ISSUE TITLE
Case Insensitive "contains" searches?

### ISSUE THREAD

**Issue by Mctalian** [hbi99/defiant.js#23]
It appears that //*[contains(key, "text")] is case sensitive only. I could apply ".toLowerCase()" to the search text, but is there a way to apply it to the key argument?

Perhaps for things that don't directly use the key or field name, you could make it its own function instead of using XPath and have an argument for case sensitive or not? Or perhaps add that in addition to the functionality that already exists?

**Comment by Mctalian** [comment]
I guess if this is mimicking XPath, then it's possible to do it:

http://stackoverflow.com/questions/8474031/case-insensitive-xpath-contains-possible

Though, as mentioned in this answer, it is incredibly ugly. Not sure if you'd still be willing to pursue this.

**Comment by hbi99** [comment]
Hi @Mctalian,
Actually this lib isn't mimicking XPath...it executes XPath as is and uses the browsers built in evaluator.

Regarding your question; yes, it is possible to search on keys. I have created a demo file that exemplifies this here:
https://github.com/hbi99/defiant.js/blob/insensitive-contains/demo/json-search-5.htm

```js
var found = JSON.search(data, "//*[contains(name(), 'title')]");

console.log( found );
```

Notice that the link I've pasted above points to a branch that is not the master-branch. The reason for this is because I've added a XPath "manipulator" so that 'contains' automatically becomes case insensitive.
```js
// instead of writing this XPath
found = JSON.search(data, "//*[contains(translate(title, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'rings')]/title");
// ...do like this instead. Defiant will make 'contains' case insensitive automatically
found = JSON.search(data, "//*[contains(title, 'rings')]/title");
```

Before merging this to the master-branch, it would be great if you test it out as well and give me feedback.

Thanks

**Comment by hbi99** [comment]
@Mctalian 
I've merged the feature branch with the master branch.
Meaning the update is available in version 1.2.2

Thanks

**Comment by Mctalian** [comment]
@hbi99 
Thank you, I will check this out today!

**Comment by Mctalian** [comment]
Works like a charm! Thank you very much!

**Comment by BlackWiCKED** [comment]
I just ran into a similar issue. It's confirmed that "fn::contains" is not case sensitive anymore, but there are other string functions that would require the same approach:

http://www.w3schools.com/xpath/xpath_functions.asp

The most painful ones (for me currently) are definitely:
1) fn:starts-with(string1,string2)
2) fn:ends-with(string1,string2)

I have not checked the full list, but there are probably more functions which can be made case-insensitive with the current method. I think it would not be hard to extend the regex part to recognize these commands as well, not just "contains" as it is in https://github.com/hbi99/defiant.js/blob/master/src/string.js line 18-30.

**Comment by hbi99** [comment]
@BlackWiCKED 
Good idea...I'll get to it this weekend.
Not sure if I remember correctly but I think that IE might not support "starts-with" and related. If it plays well, it'll definitely make master branch.

Cheers
