### ISSUE TITLE
Wrong result when evaluating an XPath expression

### ISSUE THREAD

**Issue by dnovatchev** [hbi99/defiant.js#26]
This expression:

//text()

doesn't select the text-node children of two of the three occurrences of the element "category" using the tool at: http://defiantjs.com/#xpath_evaluator

**Comment by hbi99** [comment]
Actually category keys are "captured" as well...though there is a bug in the visualization of XPath Evaluator (that I am aware of since before).

To clarify, DefiantJS returns those matches as well (look at the console of your browser). The highlighting algorithm contains a bug but that code has nothing to do with search and find part of the lib.
