### ISSUE TITLE
Is it possible to have multiple conditions on the same field.

### ISSUE THREAD

**Issue by djpate** [hbi99/defiant.js#32]
Trying to use the xpath selection to select the title of the first fiction book.

Is it doable?

```
//*[category="fiction" and .first()]/title
```

Thanks

**Comment by hbi99** [comment]
Hi @djpate,
I suspect you might be looking for an expression like this;
```
//*[category="fiction" and position() = 1]/title
```

Though, this will return an item with the category "fiction" and its "index" being first among it's siblings. For instance, this query will not return any matches (since the item "Sayings of the Century" is not preceding its siblings):

```
//*[category="reference" and position() = 1]/title
```

If you are looking for the first encountered item with the category "fiction", I suggest that you don't add another condition - since the returned array will contain all qualifying items and the array will be ordered as the items are encountered. For instance:


```js
var found = JSON.search(data, '//*[category="fiction"]/title');

console.log(found[0]);
// "Sword of Honour" --> first encountered item

console.log(found.length);
// 3
```

Finally, to answer your question; if it is possible to have multiple condition on the same field - the answer is sure, it's possible. Using "and", "or" & "not" operators, your expressions can be as filtering as you want. In such scenarios, use parenthesis correctly. If you are dealing with large JSON data, I suggest using the snapshot feature for best performance...something like this:

```js
var snapshot = Defiant.getSnapshot(data),
    found = JSON.search(snapshot, '//*[category="fiction" and ... or ...]/title');
```

Best regards

**Comment by djpate** [comment]
Thanks for you prompt reply!

I know that found[0] seems like a easy way to solve my issue but In my use case unfortunatly I can't apply extra logic. I was using JSONSelect and I had the same type of issue that I was hoping this library would fix. Seems like it's not doable but thanks for the work that you're doing it's a pretty amazing script.

**Comment by hbi99** [comment]
@djpate,
If you don't want to apply the second logic as I suggested, there is a way to solve it the way you want it;

```
//*[category="reference"][1]/author
```

Let me know if I can assist further.
Cheers

**Comment by djpate** [comment]
Oh wow, awesome! you made my day.
