### ISSUE TITLE
Searching with multiple words

### ISSUE THREAD

**Issue by samsonkhisty** [hbi99/defiant.js#35]
Hi there, 
Quick question, I want to search for multiple words separately. From the book example in the evaluator, if my search term is "word century" then I want the 1st and the 3rd book highlighted. 

I tried using the below 

     //*[contains(title,"century sword")]  <-- does not work

    //*[contains(title,"century") or contains(title,"sword")] <-- highlights only 3rd book

    //*[contains(title,"century") or contains(title,"word")] <-- highlights 1st & 3d

Not sure if something is wrong with my query string. Hopefully you can give me some pointers.

**Comment by samsonkhisty** [comment]
Looks like this is fixed. https://github.com/hbi99/defiant.js/issues/33
Apologies.

**Comment by hbi99** [comment]
@samsonkhisty 
As you noticed, this has been taken care of but to tell you the truth, the website version of the lib was not updated (sorry...). So you're right reporting the issue...thanks.

I've updated the website now...

**Comment by samsonkhisty** [comment]
No worries at all. This is a good library btw. I had another question, since you are the author, I think you'd know best. 

I am current working on an in-house support portal and researching ways of providing fast searches for users to search within the search portal. The support portal is fairly medium sized with 4 sections and each section will have articles. I have this big nested JSON object that I used to build the full view as a mockup. My JSON object has 2 values called html-content and raw-content, html to display while raw-content (concatenation of title, content and other items like tags etc) to search using defiant. Ideally a big typeahead will do the job of searching within the raw-content and display results categorized by sections. I did a basic JSON object with actual data in one of the sections and tried it in the xpath evaluator and looked good. I was wondering if defiant will work well if the data gets large in the future. Your insights will be invaluable. 

Thanks.

**Comment by hbi99** [comment]
I think you can do very fast searches and type-aheads with defiant and larger files. I have done it myself in a several projects. I can give you hints on performance and help you. You might already know this but one misstake that I see when analyzing others code is "unwanted scope-chaining". To understand what I mean, have a look at this image:

![pastedgraphic-5](https://cloud.githubusercontent.com/assets/637727/6404155/3cdd3dda-be15-11e4-9c5b-dc30fed94028.png)

When javascript is executed, in the function raf_render, the execution context stops to "find" the variable "item". If it can not find it, the context will climb in the scope ladder and looks for it there...so on and so forth (...and if the variable can't be found at the global scope, an error is thrown). This scope chaining can be a big performance thief but it also can be fixed with simple local declarations.

The execution context can access "this", "arguments" and local variables fastest and if you have this in mind when writing functions that requires speed, for instance type-ahead, I think you'll be writing real fast stuff.

I do have other tips like this, if you're interested...let me know.

**Comment by samsonkhisty** [comment]
Top tip. If I use CoffeeScript do I still need to worry about scope
chaining if I use fat arrows =>.

More Tips? Hell Yeah!


*---*
*Samson Khisty*
Manager, Design

<http://eightspokes.com/>
617.678.9802 I @eightspokes
www.linkedin.com/in/skhisty/

*NOTICE TO RECIPIENT:* If you are not the intended recipient of this
e-mail, you are prohibited from sharing, copying, or otherwise using or
disclosing its contents. If you have received this e-mail in error, please
notify the sender immediately by reply e-mail and permanently delete this
e-mail and any attachments without reading, forwarding or saving them.

**Comment by hbi99** [comment]
@samsonkhisty 
Sorry for the delayed reply...I've been really busy lately and will return with longer response.
Till then; I haven't written that much in coffeescript but I think it is possible to make unintentional scope-chaining regardless. The reason is because, scope-chaining can be "intentional" as well and using correctly, one can achieve "private variables" in javascript - as in other languages.

Consider the code below...using this setup, the variable __private_int__ is "private" and can't be affected by unauthorized script. This is useful and a secure way to protect your objects. Now, someone might say "well, I can add a breakpoint via firebug or similar and mess up the security anyway". This argument don't work if your script is minified...hence adding break points becomes difficult.

```js

var my_class = (function() {
	
	var private_int = 1;

	return {
		add: function(a) {
			private_int	+= a;
		},
		subtract: function(a) {
			private_int	-= a;
		}
	};

})();

```

I'll write more tips later on.

Cheers

**Comment by samsonkhisty** [comment]
Hi Hakan,
     Thanks for taking the time to help someone. You should blog about
these tips and tricks, this may help others too.


*---*
*Samson Khisty*
Manager, Design

<http://eightspokes.com/>
617.678.9802 I @eightspokes
www.linkedin.com/in/skhisty/

*NOTICE TO RECIPIENT:* If you are not the intended recipient of this
e-mail, you are prohibited from sharing, copying, or otherwise using or
disclosing its contents. If you have received this e-mail in error, please
notify the sender immediately by reply e-mail and permanently delete this
e-mail and any attachments without reading, forwarding or saving them.

**Comment by samsonkhisty** [comment]
Hi Hakan,

This is just an FYI. Chrome provides the pretty print option to un-minify
your script, add breakpoints & debug code.

[image: Inline image 1]

*---*
*Samson Khisty*
Manager, Design

<http://eightspokes.com/>
617.678.9802 I @eightspokes
www.linkedin.com/in/skhisty/

*NOTICE TO RECIPIENT:* If you are not the intended recipient of this
e-mail, you are prohibited from sharing, copying, or otherwise using or
disclosing its contents. If you have received this e-mail in error, please
notify the sender immediately by reply e-mail and permanently delete this
e-mail and any attachments without reading, forwarding or saving them.

**Comment by samsonkhisty** [comment]
Hakan,
     When you mentioned in the first tip about scope chaining can be a big
hit to performance. How did you go about finding out and isolating the fact
that scope chaining is the culprit. Do you use some kind of performance
tools?

Also if I understand correctly, scope chaining can be avoided by passing
item as an argument to the function or assigning them to local variables.



*---*
*Samson Khisty*
Manager, Design

<http://eightspokes.com/>
617.678.9802 I @eightspokes
www.linkedin.com/in/skhisty/

*NOTICE TO RECIPIENT:* If you are not the intended recipient of this
e-mail, you are prohibited from sharing, copying, or otherwise using or
disclosing its contents. If you have received this e-mail in error, please
notify the sender immediately by reply e-mail and permanently delete this
e-mail and any attachments without reading, forwarding or saving them.

**Comment by hbi99** [comment]
Damn Chrome...does it have to be the best browser available ;-)

Avoiding scope chaining has affected how I write code. IMHO, being aware of it is enough.
Occasionally, I do check out performance in Chrome developer tools...especially when doing game development. I enjoyed this IO-talk from 2012;
https://www.youtube.com/watch?v=hAzhayTnhEI

*good stuff*
