### ISSUE TITLE
when XSLTProcessor is undefined

### ISSUE THREAD

**Issue by ehab2012** [hbi99/defiant.js#52]
hello
first thanks for the effort put in this project.
I am using PhantomJS and since XSLTProcessor is not supported the ie.polyfill.js can be improved to at least add a message like so
```
if (typeof (data.transformNode) != "undefined") {
					var str = data.transformNode(this.xsldoc),
					span = document.createElement('span');
					span.innerHTML = str;
					return span;
				}
				else {
					span = document.createElement('span');
					span.innerHTML = "XSLTProcessor transformNode not implemented";
					return  span;
				}
```
i was trying to add support myself but looks like it needs more time if ever it was easy.
Thanks and thats all for now.
ehab

**Comment by hbi99** [comment]
thanks @ehab2012,
Added such support...though, instead of appending a SPAN-element, I think it is better to throw an error.

```js
if (typeof(XSLTProcessor) === 'undefined') {
    ...
} else {
	// throw error
	throw 'XSLTProcessor transformNode not implemented';
}
```

Cheers

**Comment by zuozp8** [comment]
@hbi99 
in v1.3.2  defiand always throws exception 'XSLTProcessor transformNode not implemented' on chrome and firefox

**Comment by hbi99** [comment]
@zuozp8 
You're right...I added a fix and I think it will work for PhantomJS and browser environment.

Cheers

**Comment by ehab2012** [comment]
may i ask if implementation for the XSLTProcessor  is planned?
I see this as essential complement to defiant.js 

i would love to help out but i am in between too many distraction i cannot find time right now?
Thanks for any consideration by anyone.

**Comment by hbi99** [comment]
@ehab2012 
I do have plans to make this work in node-environment and made some investigations on requirements and what not about a year ago. There were a lot of dependencies required in order to make it work. I decided to wait since some of the dependencies were not enough mature (IMHO).

Furthermore, I really want to make it work with hygienic approach in mind...many libs out there have  (deep) dependencies and these do have impact on projects utilizing the libs...I think it might be sane to add node-support carefully rather that fast and unconsidered.

**Comment by ehab2012** [comment]
i agree about running out of the box approach and node support is a definite must have these days.
if i did get sometime i will make noise again :)
have a nice week.
