### ISSUE TITLE
Safari 8: XSLTProcessor existed BUT still throw "XSLTProcessor transformNode not implemented"

### ISSUE THREAD

**Issue by tkyeung357** [hbi99/defiant.js#55]
![screen shot 2015-09-15 at 4 01 45 pm](https://cloud.githubusercontent.com/assets/3213251/9871012/44980df6-5bc3-11e5-95b0-3194567ff373.png)
![screen shot 2015-09-15 at 3 59 06 pm](https://cloud.githubusercontent.com/assets/3213251/9871014/44eeffc6-5bc3-11e5-8419-c19ad4ea8d63.png)

**Comment by hbi99** [comment]
@tkyeung357 
Thanks for the report...this is fixed in v1.3.3

**Comment by tkyeung357** [comment]
@hbi99 
hi, actually i already use v1.3.3. 
attached a screenshot for your reference.
![bugfix_ _hbi99_defiant_js_116ae94](https://cloud.githubusercontent.com/assets/3213251/9899249/349912d8-5c8b-11e5-9c53-a81b9eb4ba33.png)

**Comment by hbi99** [comment]
@tkyeung357 
Thanks to this pull-request, I realised that package version was not synced with release version. The new version of 1.3.3 that you tested is actually 1.3.2.

Anywho, in order to remove this problem, I have created a new version and release; v1.3.4
Please try it out and if you still have problems, I'll fix it.

Regards
