### ISSUE TITLE
Alphanumeric keys

### ISSUE THREAD

**Issue by AVSYS-AK** [hbi99/defiant.js#56]
Hi,

I am trying to search json with alphanumeric keys. Its failing to search.

here is my json. I would really appreciate your help.

"sizes": [
                {
                    "L": "20/18",
                    "M": "10/7",
                    "S": "30/26",
                    "2XL": "50/20",
                    "color": "MIX"
                },
                {
                    "L": "10/6",
                    "M": "10/6",
                    "S": "10/8",
                    "2XL": "20/18",
                    "color": "SR"
                },
                {
                    "L": "10/7",
                    "M": "30/26",
                    "S": "50/20",
                    "3XL": "10/6",
                    "color": "MIX"
                },
                {
                    "L": "10/6",
                    "M": "10/8",
                    "S": "20/18",
                    "XL": "10/7",
                    "color": "BL"
                },
                {
                    "L": "30/26",
                    "M": "50/20",
                    "S": "10/6",
                    "3XL": "10/6",
                    "color": "FGN"
                }
            ]

**Comment by hbi99** [comment]
Hi @AVSYS-AK,
The reason for failure is the keys starting with a number...for instance "3XL". Keys such as these causes failure - the basic idea behind DefiantJS is that it transforms (or tries its best) JSON data into XML. Any XPath expressions made will be on that transformed XML document.

Now, since a node name can not start with an integer, the transform would fail - but, I thought about this exception and chose to handle such situations...though, this means that you'll have to write a "special" XPath.

Check out this JSFiddle I've created for you:
http://jsfiddle.net/hbi99/8hxmf376/

I think you should understand the solution - or at least use it for your benefit.

Cheers

**Comment by AVSYS-AK** [comment]
Thanks @hbi99 , well i did go ahead to write my own XPath, but your answer helped boost the confidence.. m a noob :D

Cheers mate.
