### ISSUE TITLE
Stream json ?

### ISSUE THREAD

**Issue by stuaxo** [hbi99/defiant.js#59]
Using something like oboe progressive-json it should be possible to match xpath rules as json is being downloaded.

http://oboejs.com/api

https://github.com/antimatter15/progressive-json

**Comment by hbi99** [comment]
@stuaxo,
OboeJS looks interesting, though in order to support in the way you suggest, defiant will need some extended code.

When reading about OboeJS and progressive-suggestions you're writing about - I relate a lot to concurrency and asynchronous programming issues experienced these days. To address these issues, I've been working on library that I think can be a solution; QureJS - with which code flow, concurrency and async code becomes a lot easier. Check out the examples in these demo-files to get an idea;

https://github.com/hbi99/QureJS/tree/master/demo

**Comment by hbi99** [comment]
@stuaxo,
If you don't mind, I would like to close this issue since it not really a bug...but more an enhancement.

**Comment by stuaxo** [comment]
No prob, cheers :)
