### ISSUE TITLE
Uncaught JSON data should not contain functions. Please check jour structure.

### ISSUE THREAD

**Issue by abbasovalex** [hbi99/defiant.js#61]
There is a difference between https://github.com/hbi99/defiant.js/blob/master/dist/defiant.js#L396 and https://github.com/hbi99/defiant.js/blob/master/dist/defiant-latest.js#L248 files.

I had problem with IE10+ and trying use https://github.com/hbi99/defiant.js/blob/master/dist/defiant.js version but I get the exception. My original JSON here http://pastebin.com/4sNGLcsf

There is a simple example that raises same exception:
JSON.toXML({'a': {'b': false, 'c': [12,3]}})

Is it right? What are you think? 

Thanks!

**Comment by hbi99** [comment]
Hi @abbasovalex,
That exception is raised if there is a property in your JSON that is a function. Since this is not allowed in JSON, I've added this exception handler and notify the developer about this fault.

Regarding the simple example that you have pasted in; I have tested that code on this file:
http://www.defiantjs.com/defiant.js/demo/json-xml-3.htm

...and it does not raise any error in IE11 (see the screenshot). I can help you troubleshoot, though I'd suggest that you create a JSFiddle version. That might simplify for us to zoom into the problem.

Best regards

![image](https://cloud.githubusercontent.com/assets/637727/11171481/9e5720b2-8bf1-11e5-85c2-1f3a0b8dbe97.png)

**Comment by hbi99** [comment]
@abbasovalex,
Closing this issue...if you disagree or want help, re-open it. Ok?

**Comment by AdityaDekate** [comment]
Hello Sir
I am still getting error Uncaught JSON data should not contain functions. Please check jour structure.
My json is {"PayConfigs":[{"AccuralCode":"test","PayCode":"test"},{"AccuralCode":"test2","PayCode":"test2"}]}

**Comment by clispedreira** [comment]
I found the same error but I get what's wrong: when a stringfied JSON is sent or something that is not a JSON, error happens.

Error example:
```
f = ({'a': {'b': false, 'c': [12,3]}});
g = JSON.search(a, "*//c");

**result -> "JSON data should not contain functions. Please check your structure."**
```


Another error example:
```
f = JSON.stringify({'a': {'b': false, 'c': [12,3]}});
g = JSON.search(a, "*//c");

**result -> "JSON data should not contain functions. Please check your structure."**
```


But this works right:
```
f = JSON.stringify({'a': {'b': false, 'c': [12,3]}});
g = JSON.parse(f)
h  = JSON.search(g, "*//c")

**result OK -> [12, 3]** 
```

Hope this can help!
