### ISSUE TITLE
Current version is ????

### ISSUE THREAD

**Issue by netaisllc** [hbi99/defiant.js#65]
This looks like a great project and I'm attempting to use it in conjunction with JSPM and its module loader. I can't quite figure out the currently supported release version.  

Bower.json and Package.json indicate **1.3.5.**  But loading ./dist/defiant.min.js results in a run time error (JSON.search is undefined.)

Using ./dist/defiant-latest.min seems to work as expected, but its code suggests it is version **1.2.5**.

It's pretty confusing to have both _defiant_ and _defiant-latest_ in the dist folder.  What's your intention about this? And which version do you recommend for a real (non-toy) app?

Thanks!

**Comment by hbi99** [comment]
@netaisllc,
Sorry about this...I started migration from Grunt to Gulp and a couple of hours ago, I made a release that turned out to be buggy. The gulp file is updated and the issue has beed attended to - and a new version is available `1.3.6`. I have also cleaned out the '-latest' files from the dist folder.

Thanks for the heads-up.
