### ISSUE TITLE
Can't be used with Rhino because it assumes there is a navigator

### ISSUE THREAD

**Issue by sglebs** [hbi99/defiant.js#71]
If you try to import this JS into Rhino, it bombs: "navigator" is not defined.
I presume the same will happen if you try it with NodeJS.
Is it possible to remove this dependency on the browser? I am interested in using this library with server-side code in JS.

Thanks for listening.

**Comment by hbi99** [comment]
Hi @sglebs,
Making this lib work in Node environment is on my to-do list and I think it can be done. The problem is that it will require large nested dependency list which in my humble opinion is bad way to go. I don't want to be one of those developers that contribute to this careless setup that delivers insane dependencies with a library. Instead, I have chosen to await either a genius idea or something that might be added to the core of Node, that might facilitate the implementation.

**Comment by ss108** [comment]
@hbi99 is there some work around we can use to make this work in Node? @sglebs did you find a way to remove the browser dependency? or simulate it? 

thanks

**Comment by muralinit** [comment]
Hi @hbi99,

I am also waiting for this feature to complete from long time. Can you please let me know by when we can have this feature.

**Comment by hbi99** [comment]
Hi @matthiaskaemi,
I did publish a first version of the Node version in a feature version.
https://github.com/hbi99/defiant.js/issues/4#issuecomment-396385438

Check it out and feedback are welcome

**Comment by hbi99** [comment]
I think this is solved - if you still have problems, please re-open it or create a new issue. PReferably with sample code. Cheers
