### ISSUE TITLE
[BUG] Problem with JSON.search

### ISSUE THREAD

**Issue by tguillemot** [hbi99/defiant.js#79]
First of all, thank you for defiant.js.
I'm just a beginner but I think there is a bug with the v.1.4.0 of  `JSON.search`.

Let's consider the JSON (called `json` later):
```
{
    "key" : "value",
    "array" : [
        { "key" : 1 },
        { "key" : 2, "dictionary": {
                "a": "Apple",
                "b": "Butterfly",
                "c": "Cat",
                "d": "Dog"
            } },
        { "key" : 3 }
    ]
}
```
For the search : `JSON.search(json, '//key')`, the results are ok :
```
["value", 1, 2, 3]
```
but for `JSON.search(json, '/key')` the result is :
```
[]
```
rather than `"value"`.

As I'm not an expert of XPath, maybe I'm doing something wrong.

**Comment by hbi99** [comment]
Hi @tguillemot,
The correct way to match "key", in the root is (XPath):

/*/key

I understand why you might find this as confusing but there is actually a reason. In order to query the JSON data with XPath, it is transformed to XML. When done, the XPath is applied to XML and the corresponding key/value is then returned as an array.

In XML, only one node can be "root" node, hence a a root is added that "does not match" JSON data...actually this rule applies to JSON as well - meaning, it can only have one root node but the root node in JSON maps to the variable name.

**Comment by tguillemot** [comment]
@hbi99 Ha ok sorry for my mistake.
Thank you for your help :)
